# Generated by Django 2.1.8 on 2019-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('admission_year', models.IntegerField()),
                ('student_number', models.IntegerField()),
                ('level', models.IntegerField()),
                ('grade_avg', models.FloatField()),
            ],
        ),
    ]
